/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  umouse_scfkuwaganon                    */
/*      FILE         :  umouse_scfkuwaganon.cpp                */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <iodefine.h>
#include <stdio.h>
#include <stdarg.h>

// HardwareAbstractionLayer
#include "hal_clock.h"
#include "hal_timer.h"
#include "hal_uart.h"


// プロトタイプ宣言
void halInit();
void startUpInit();
void object_init();


#ifdef CPPAPP
//Initialize global constructors
extern void __main() {
    static int initialized;
    if (! initialized) {
        typedef void (*pfunc) ();
        extern pfunc __ctors[];
        extern pfunc __ctors_end[];
        pfunc* p;

        initialized = 1;
        for (p = __ctors_end; p > __ctors; )
            (*--p) ();

    }
}
#endif

int main(void) {
    halInit();
    startUpInit();
    while(1) {
        char hoge[100];
        sprintf( &hoge[0], "0123456789\n" );
        // TODO: add application code here
        hal::waitmsec(1000);
        hal::putnbyteUart0((uint8_t *)hoge, 10);
        hal::putnbyteUart1((uint8_t *)hoge, 10);
        hal::sendDataUart1();
    }
    return 0;
}

//各ペリフェラルの初期化
void halInit() {    
    hal::initClock();
    hal::initTimer();
    hal::initUart0();
    hal::initUart1();
}


//起動時の処理
void startUpInit() {

}


void object_init() {

}


