/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  umouse_scfkuwaganon                    */
/*      FILE         :  umouse_scfkuwaganon.cpp                */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <iodefine.h>
#include <stdio.h>
#include <stdarg.h>

// HardwareAbstractionLayer
#include "hal_clock.h"
#include "hal_timer.h"


// プロトタイプ宣言
void halInit();
void startUpInit();
void object_init();


#ifdef CPPAPP
//Initialize global constructors
extern void __main() {
    static int initialized;
    if (! initialized) {
        typedef void (*pfunc) ();
        extern pfunc __ctors[];
        extern pfunc __ctors_end[];
        pfunc* p;

        initialized = 1;
        for (p = __ctors_end; p > __ctors; )
            (*--p) ();

    }
}
#endif

int main(void) {
    halInit();
    startUpInit();
    while(1) {
        char hoge[100];
        sprintf( hoge, "[WARNING] " );
        // TODO: add application code here
    }
    return 0;
}

//各ペリフェラルの初期化
void halInit() {
    //クロック
    hal::initClock();
    hal::initTimer();

}


//起動時の処理
void startUpInit() {

}


void object_init() {

}


